In [1]:
import MetaTrader5 as mt5
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

import matplotlib.dates as mpl_dates
import matplotlib.pyplot as plt

from datetime import datetime 
import schedule
import time

In [2]:
# Create the bound between MT5 and Python
mt5.initialize()

True

# Importando Datos MT5

https://www.mql5.com/es/docs/python_metatrader5

In [3]:
def Simbolo(divisa, tf,em,ter):  
           
    temp = {'M1':mt5.TIMEFRAME_M1,'M5':mt5.TIMEFRAME_M5,
            'M15':mt5.TIMEFRAME_M15,'M30':mt5.TIMEFRAME_M30,
            'H1':mt5.TIMEFRAME_H1,'H4':mt5.TIMEFRAME_H4
           }
    for clave, cont in temp.items():
        if tf == clave:
            rates = mt5.copy_rates_from_pos(divisa, cont, em, ter)

    # Transform Tuple into a DataFrame
    df_rates = pd.DataFrame(rates).dropna()
    

    # Convert number format of the date into date format
    df_rates["time"] = pd.to_datetime(df_rates["time"], unit="s")
    df_rates = df_rates.drop(['tick_volume','spread','real_volume'],axis=1)
    
    df_rates.time = pd.to_datetime(df_rates['time'])
    df_rates.index = df_rates.time
    df_rates.index.name = 'date'
    df_rates['time'] = df_rates['time'].apply(mpl_dates.date2num)

    return df_rates

symbol    = 'EURUSD'
timeframe = 'M1'
ini = 0
ter = 1000
df = Simbolo(symbol,timeframe,ini,ter)
df.head()

                             time     open     high      low    close
date
2023-05-02 03:59:00  19479.165972  1.09786  1.09791  1.09786  1.09789
2023-05-02 04:00:00  19479.166667  1.09788  1.09806  1.09785  1.09805
2023-05-02 04:01:00  19479.167361  1.09805  1.09822  1.09803  1.09821
2023-05-02 04:02:00  19479.168056  1.09821  1.09828  1.09817  1.09828
2023-05-02 04:03:00  19479.168750  1.09828  1.09828  1.09817  1.09822

# SuperTrend (ATR)

In [4]:
def SuperTrend(df):
    #ATR
    high_low = np.abs(df['high'] - df['low'])
    high_pc = np.abs(df['high'] - df['close'].shift(1))
    low_pc = np.abs(df['low'] - df['close'].shift(1))

    ranges = pd.concat([high_low, high_pc, low_pc],axis=1)
    true_range = np.max(ranges, axis=1)
    df['atr'] = true_range.rolling(7).mean() #14
    
    multiplier = 3
    df['upperband'] = ((df.high + df.low) / 2) + (multiplier * df.atr)
    df['lowerband'] = ((df.high + df.low) / 2) - (multiplier * df.atr)
    df['in_uptrend'] = True
    
    for current in range(1, len(df.index)):
        previous = current - 1

        if df['close'][current] > df['upperband'][previous]:
            df['in_uptrend'] = True
        elif df['close'][current] < df['lowerband'][previous]:
            df['in_uptrend'] = False
        else:
            df['in_uptrend'][current] = df['in_uptrend'][previous]

            if df['in_uptrend'][previous] and df['lowerband'][current] < df['lowerband'][previous]:
                df['lowerband'][current] = df['lowerband'][previous]

            if not df['in_uptrend'][current] and df['upperband'][current] > df['upperband'][previous]:
                df['upperband'][current] = df['upperband'][previous]
    
    return df

st = SuperTrend(df)
st.tail(10)

,time,open,high,low,close,atr,upperband,lowerband,in_uptrend
date,,,,,,,,,
2023-05-02 20:29:00,19479.853472,1.09980,1.09988,1.09979,1.09988,0.000076,1.099882,1.099608,True
2023-05-02 20:30:00,19479.854167,1.09988,1.09995,1.09983,1.09989,0.000081,1.100134,1.099646,True
2023-05-02 20:31:00,19479.854861,1.09989,1.10011,1.09989,1.10010,0.000099,1.100296,1.099704,True
2023-05-02 20:32:00,19479.855556,1.10010,1.10020,1.10005,1.10015,0.000114,1.100468,1.099782,True
2023-05-02 20:33:00,19479.856250,1.10015,1.10015,1.10005,1.10012,0.000114,1.100443,1.099782,True
2023-05-02 20:34:00,19479.856944,1.10013,1.10016,1.10008,1.10016,0.000114,1.100463,1.099782,True
2023-05-02 20:35:00,19479.857639,1.10017,1.10020,1.10013,1.10014,0.000119,1.100521,1.099809,True
2023-05-02 20:36:00,19479.858333,1.10015,1.10015,1.10004,1.10008,0.000121,1.100459,1.099809,True
2023-05-02 20:37:00,19479.859028,1.10009,1.10014,1.10001,1.10004,0.000123,1.100444,1.099809,True
2023-05-02 20:38:00,19479.859722,1.10004,1.10014,1.10003,1.10014,0.000107,1.100406,1.099809,True

In [13]:
def send_order(symbol, lot, buy, sell, id_position=None, comment=" No specific comment", magic=0):
    
    # Initialize the bound between MT5 and Python
    mt5.initialize()
    
    # Extract filling_mode
    filling_type = mt5.symbol_info(symbol).filling_mode
        
    """ OPEN A TRADE """
    if buy and id_position==None:
        price = mt5.symbol_info_tick(symbol).ask
        sl = price - (1 * 0.01)
        tp = price + (2 * 0.01)
        request = {
        "action": mt5.TRADE_ACTION_DEAL,
        "symbol": symbol,
        "volume": lot,
        "type": mt5.ORDER_TYPE_BUY,
        "price": price,
        "sl": sl,
        "tp": tp,
        "deviation": 10,
        "magic": magic,
        "comment": comment,
        "type_filling": filling_type,
        "type_time": mt5.ORDER_TIME_GTC}
        
        result = mt5.order_send(request)
        return result
        
    if sell and id_position==None:
        price = mt5.symbol_info_tick(symbol).bid
        sl = price - (1 * 0.01)
        tp = price + (2 * 0.01)
        request = {
        "action": mt5.TRADE_ACTION_DEAL,
        "symbol": symbol,
        "volume": lot,
        "type": mt5.ORDER_TYPE_SELL,
        "price": price,
        "sl": sl,
        "tp": tp,
        "deviation": 10,
        "magic": magic,
        "comment": comment,
        "type_filling": filling_type,
        "type_time": mt5.ORDER_TIME_GTC}
        
        result = mt5.order_send(request)
        return result
    
    """ CLOSE A TRADE """
    if buy and id_position!=None:
        request = {
        "position": id_position,
        "action": mt5.TRADE_ACTION_DEAL,
        "symbol": symbol,
        "volume": lot,
        "type": mt5.ORDER_TYPE_SELL,
        "price": mt5.symbol_info_tick(symbol).bid,
        "deviation": 10,
        "magic": magic,
        "comment": comment,
        "type_filling": filling_type,
        "type_time": mt5.ORDER_TIME_GTC}
        
        result = mt5.order_send(request)
        return result
        
    if sell and id_position!=None:
        request = {
        "position": id_position,
        "action": mt5.TRADE_ACTION_DEAL,
        "symbol": symbol,
        "volume": lot,
        "type": mt5.ORDER_TYPE_BUY,
        "price": mt5.symbol_info_tick(symbol).ask,
        "deviation": 10,
        "magic": magic,
        "comment": comment,
        "type_filling": filling_type,
        "type_time": mt5.ORDER_TIME_GTC}
        
        result = mt5.order_send(request)
        return result

In [6]:
posicion = False 

def señales_compra_o_venta(df, symbol):
    global posicion
      
    print('buscando señales..........','\n\n')
    
    ultima_fila    = len(df.index) - 1
    penultima_fila = ultima_fila - 1
    
    if not df['in_uptrend'][penultima_fila] and df['in_uptrend'][ultima_fila]:
        print('Cambio de tendencia, COMPRAR','\n')
        if not posicion:
            print(send_order(symbol, 0.01, True, False))
            posicion = True
        else:
            print('Ya se encuentra en posicion de COMPRA')
           
    if df['in_uptrend'][penultima_fila] and not df['in_uptrend'][ultima_fila]:
        print('Cambio de tendencia, VENTA','\n')
        if posicion:
            print(send_order(symbol, 0.01, False, True))
            posicion = False
        else:
            print('Ya se encuentra en posicion de VENTA')

In [7]:
def run_bot():
#     print(f'Buscando barras nuevas desde: {datetime.now().isoformat()}','\n')
    data   = Simbolo(symbol,timeframe,0,50)
    print(f'Buscando barras nuevas desde: {data.index[-1]}','\n')
    STdata = SuperTrend(data)
    señales_compra_o_venta(STdata, symbol)

# temp = {'M1':1,'M5':5,'M15':15,'M30':30,'H1':60,'H4':240}

# for clave, contenidos in temp.items():
#     if timeframe == clave: 
#         schedule.every(contenidos).minutes.do(run_bot)
schedule.every(1).minute.do(run_bot)

while True:
    schedule.run_pending()
    
    time.sleep(1)

Buscando barras nuevas desde: 2023-05-02 20:41:00

buscando señales..........


Buscando barras nuevas desde: 2023-05-02 20:42:00

buscando señales..........


Buscando barras nuevas desde: 2023-05-02 20:43:00

buscando señales..........


Buscando barras nuevas desde: 2023-05-02 20:44:00

buscando señales..........


Buscando barras nuevas desde: 2023-05-02 20:45:00

buscando señales..........


Buscando barras nuevas desde: 2023-05-02 20:46:00

buscando señales..........


Buscando barras nuevas desde: 2023-05-02 20:47:00

buscando señales..........


Buscando barras nuevas desde: 2023-05-02 20:48:00

buscando señales..........


Buscando barras nuevas desde: 2023-05-02 20:49:00

buscando señales..........

KeyboardInterrupt:

In [ ]:
# Create the bound between MT5 and Python
mt5.shutdown()