In [ ]:
# !pip install pywhatkit

In [1]:
import MetaTrader5 as mt5
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

import matplotlib.dates as mpl_dates
import matplotlib.pyplot as plt

from datetime import datetime 
import schedule
import time

import pywhatkit

In [2]:
# Create the bound between MT5 and Python
mt5.initialize()

True

# Importando Datos MT5

In [3]:
def Simbolo(divisa, tf,em,ter):  
           
    temp = {'M1':mt5.TIMEFRAME_M1,'M5':mt5.TIMEFRAME_M5,
            'M15':mt5.TIMEFRAME_M15,'M30':mt5.TIMEFRAME_M30,
            'H1':mt5.TIMEFRAME_H1,'H4':mt5.TIMEFRAME_H4
           }
    for clave, cont in temp.items():
        if tf == clave:
            rates = mt5.copy_rates_from_pos(divisa, cont, em, ter)

    # Transform Tuple into a DataFrame
    df_rates = pd.DataFrame(rates).dropna()
    

    # Convert number format of the date into date format
    df_rates["time"] = pd.to_datetime(df_rates["time"], unit="s")
    df_rates = df_rates.drop(['tick_volume','spread','real_volume'],axis=1)
    
    df_rates.time = pd.to_datetime(df_rates['time'])
    df_rates.index = df_rates.time
    df_rates.index.name = 'date'
    df_rates['time'] = df_rates['time'].apply(mpl_dates.date2num)

    return df_rates

symbol    = 'EURUSD'
timeframe = 'M1'
ini = 0
ter = 1000
df = Simbolo(symbol,timeframe,ini,ter)
df.head()

                             time     open     high      low    close
date
2023-05-02 07:37:00  19479.317361  1.09796  1.09817  1.09796  1.09815
2023-05-02 07:38:00  19479.318056  1.09816  1.09822  1.09816  1.09818
2023-05-02 07:39:00  19479.318750  1.09818  1.09826  1.09797  1.09797
2023-05-02 07:40:00  19479.319444  1.09795  1.09804  1.09794  1.09798
2023-05-02 07:41:00  19479.320139  1.09797  1.09814  1.09797  1.09813

# SuperTrend (ATR)

In [4]:
def SuperTrend(df):
    #ATR
    high_low = np.abs(df['high'] - df['low'])
    high_pc = np.abs(df['high'] - df['close'].shift(1))
    low_pc = np.abs(df['low'] - df['close'].shift(1))

    ranges = pd.concat([high_low, high_pc, low_pc],axis=1)
    true_range = np.max(ranges, axis=1)
    df['atr'] = true_range.rolling(7).mean() #14
    
    multiplier = 3
    df['upperband'] = ((df.high + df.low) / 2) + (multiplier * df.atr)
    df['lowerband'] = ((df.high + df.low) / 2) - (multiplier * df.atr)
    df['in_uptrend'] = True
    
    for current in range(1, len(df.index)):
        previous = current - 1

        if df['close'][current] > df['upperband'][previous]:
            df['in_uptrend'] = True
        elif df['close'][current] < df['lowerband'][previous]:
            df['in_uptrend'] = False
        else:
            df['in_uptrend'][current] = df['in_uptrend'][previous]

            if df['in_uptrend'][previous] and df['lowerband'][current] < df['lowerband'][previous]:
                df['lowerband'][current] = df['lowerband'][previous]

            if not df['in_uptrend'][current] and df['upperband'][current] > df['upperband'][previous]:
                df['upperband'][current] = df['upperband'][previous]
    
    return df

st = SuperTrend(df)
st.tail(10)

,time,open,high,low,close,atr,upperband,lowerband,in_uptrend
date,,,,,,,,,
2023-05-03 00:14:00,19480.009722,1.09977,1.09977,1.09972,1.09972,0.000034,1.099841,1.099642,True
2023-05-03 00:15:00,19480.010417,1.09982,1.09994,1.09980,1.09994,0.000064,1.100063,1.099677,True
2023-05-03 00:16:00,19480.011111,1.09994,1.09997,1.09979,1.09990,0.000090,1.100150,1.099677,True
2023-05-03 00:17:00,19480.011806,1.09982,1.09995,1.09982,1.09995,0.000103,1.100194,1.099677,True
2023-05-03 00:18:00,19480.012500,1.09994,1.10003,1.09987,1.10003,0.000120,1.100310,1.099677,True
2023-05-03 00:19:00,19480.013194,1.10004,1.10019,1.09996,1.10019,0.000141,1.100499,1.099677,True
2023-05-03 00:20:00,19480.013889,1.10014,1.10027,1.10000,1.10024,0.000177,1.100666,1.099677,True
2023-05-03 00:21:00,19480.014583,1.10024,1.10028,1.10008,1.10027,0.000199,1.100776,1.099677,True
2023-05-03 00:22:00,19480.015278,1.10028,1.10028,1.10026,1.10026,0.000170,1.100780,1.099760,True
2023-05-03 00:23:00,19480.015972,1.10027,1.10028,1.10013,1.10028,0.000166,1.100702,1.099760,True

In [5]:
def mensaje(symbol,texto):
    # Usamos Un try-except
    try:
        # Enviamos el mensaje
        if texto == 'Compra':
            day = datetime.now().isoformat()
            pywhatkit.sendwhatmsg("+573002479014",
                                f"COMPRA en {symbol}",
                                int(day[11:13]),int(day[14:16])+1)
            return print("Mensaje Enviado")
        else:
            day = datetime.now().isoformat()
            pywhatkit.sendwhatmsg("+573002479014",
                                f"VENTA en {symbol}",
                                int(day[11:13]),int(day[14:16])+1)
            return print("Mensaje Enviado")

    except:
        return print("Ocurrio Un Error")

In [6]:
posicion = False 

def señales_compra_o_venta(df, symbol):
    global posicion
      
    print('buscando señales..........','\n\n')
    
    ultima_fila    = len(df.index) - 1
    penultima_fila = ultima_fila - 1
    
    if not df['in_uptrend'][penultima_fila] and df['in_uptrend'][ultima_fila]:
        print('Cambio de tendencia, COMPRAR','\n')
        if not posicion:
            mensaje(symbol,'Compra')
            posicion = True
        else:
            print('Ya se encuentra en posicion de COMPRA')
           
    if df['in_uptrend'][penultima_fila] and not df['in_uptrend'][ultima_fila]:
        print('Cambio de tendencia, VENTA','\n')
        if posicion:
            mensaje(symbol,'Venta')
            posicion = False
        else:
            print('Ya se encuentra en posicion de VENTA')

In [8]:
def run_bot():
#     print(f'Buscando barras nuevas desde: {datetime.now().isoformat()}','\n')
    data   = Simbolo(symbol,timeframe,0,50)
    print(f'Buscando barras nuevas desde: {data.index[-1]}','\n')
    STdata = SuperTrend(data)
    señales_compra_o_venta(STdata, symbol)

# temp = {'M1':1,'M5':5,'M15':15,'M30':30,'H1':60,'H4':240}

# for clave, contenidos in temp.items():
#     if timeframe == clave: 
#         schedule.every(contenidos).minutes.do(run_bot)
schedule.every(1).minute.do(run_bot)

while True:
    schedule.run_pending()
    
    time.sleep(1)

Buscando barras nuevas desde: 2023-05-03 00:33:00

buscando señales..........


Buscando barras nuevas desde: 2023-05-03 00:34:00

buscando señales..........


Buscando barras nuevas desde: 2023-05-03 00:34:00

buscando señales..........


Buscando barras nuevas desde: 2023-05-03 00:34:00

buscando señales..........


Buscando barras nuevas desde: 2023-05-03 00:34:00

buscando señales..........


Buscando barras nuevas desde: 2023-05-03 00:36:00

buscando señales..........


Buscando barras nuevas desde: 2023-05-03 00:36:00

buscando señales..........


Buscando barras nuevas desde: 2023-05-03 00:37:00

buscando señales..........


Buscando barras nuevas desde: 2023-05-03 00:37:00

buscando señales..........


Buscando barras nuevas desde: 2023-05-03 00:37:00

buscando señales..........


Buscando barras nuevas desde: 2023-05-03 00:37:00

buscando señales..........


Buscando barras nuevas desde: 2023-05-03 00:38:00

buscando señales..........


Buscando barras nuevas desde: 2023-05-03 00:38:00

buscando señales..........


Buscando barras nuevas desde: 2023-05-03 00:39:00

buscando señales..........


Buscando barras nuevas desde: 2023-05-03 00:39:00

buscando señales..........


Buscando barras nuevas desde: 2023-05-03 00:41:00

buscando señales..........


Buscando barras nuevas desde: 2023-05-03 00:41:00

buscando señales..........


Buscando barras nuevas desde: 2023-05-03 00:42:00

buscando señales..........


Buscando barras nuevas desde: 2023-05-03 00:42:00

buscando señales..........


Buscando barras nuevas desde: 2023-05-03 00:43:00

buscando señales..........


Buscando barras nuevas desde: 2023-05-03 00:43:00

buscando señales..........


Buscando barras nuevas desde: 2023-05-03 00:44:00

buscando señales..........


Buscando barras nuevas desde: 2023-05-03 00:44:00

buscando señales..........


Buscando barras nuevas desde: 2023-05-03 00:45:00

buscando señales..........


Buscando barras nuevas desde: 2023-05-03 00:45:00

buscando señales..........


Buscando barras nuevas desde: 2023-05-03 00:46:00

buscando señales..........


Buscando barras nuevas desde: 2023-05-03 00:46:00

buscando señales..........


Buscando barras nuevas desde: 2023-05-03 00:47:00

buscando señales..........


Buscando barras nuevas desde: 2023-05-03 00:47:00

buscando señales..........


Buscando barras nuevas desde: 2023-05-03 00:48:00

buscando señales..........


Buscando barras nuevas desde: 2023-05-03 00:48:00

buscando señales..........


Buscando barras nuevas desde: 2023-05-03 00:49:00

buscando señales..........


Buscando barras nuevas desde: 2023-05-03 00:49:00

buscando señales..........


Buscando barras nuevas desde: 2023-05-03 00:50:00

buscando señales..........


Buscando barras nuevas desde: 2023-05-03 00:50:00

buscando señales..........


Buscando barras nuevas desde: 2023-05-03 00:51:00

buscando señales..........


Buscando barras nuevas desde: 2023-05-03 00:51:00

buscando señales..........

KeyboardInterrupt:

In [ ]:
# Create the bound between MT5 and Python
mt5.shutdown()